# https://github.com/calintat/minimal

baseURL = "https://asopposedtowhat.com/"
languageCode = "en-us"
title = "AsOpposedToWhat.com"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "A collection of thought provoking and possibly entertaining essays."
    githubUsername = "#"
    accent = "purple"
    showBorder = true
    backgroundColor = "white"
    font = "Libre Baskerville" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]



[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = 3
  [[menu.main]]
    identifier = "church"
    name = "WootCatChurch"
    title = "Church"
    url = "https://wootcatchurch.com"
    weight = 4

# https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted


[markup.goldmark.renderer]
    unsafe= true

# 
# 
# 
# 
# [[menu.main]]
#     url = "/"
#     name = "Home"
#     weight = 1
# 
# [[menu.main]]
#     url = "/about/"
#     name = "About"
#     weight = 2
# 
# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 3
# 
# # [[menu.main]]
# #     url = "/project/"
# #     name = "Projects"
# #     weight = 4
# 
# # Social icons to be shown on the right-hand side of the navigation bar.
# # The "name" field should match the name of the icon in Font Awesome.
# # The list of available icons can be found at http://fontawesome.io/icons.
# 
# [[menu.icon]]
#     url = "mailto:stevei@asopposedtowhat.com"
#     name = "fas fa-envelope"
#     weight = 1
# 
# # [[menu.icon]]
# #     url = "https://github.com/username/"
# #     name = "fab fa-github"
# #     weight = 2
# # 
# # [[menu.icon]]
# #     url = "https://twitter.com/username/"
# #     name = "fab fa-twitter"
# #     weight = 3
# # 
# # [[menu.icon]]
# #     url = "https://www.linkedin.com/in/username/"
# #     name = "fab fa-linkedin"
# #     weight = 4
# # 
# # [[menu.icon]]
# #     url = "https://www.stackoverflow.com/username/"
# #     name = "fab fa-stack-overflow"
# #     weight = 5


