baseURL = "https://asopposedtowhat.com"
languageCode = "en-us"
title = "AsOpposedToWhat.com"

# See themes/tale/layouts/partials/head.html
# googleAnalytics = "UA-88355709-2"

# https://gohugo.io/templates/internal/

googleAnalytics = 'G-B4P34ZJVFM'

# theme = "newsroom"
# theme = "bootstrap"
### theme = "tale"

# https://fonts.google.com/specimen/Libre+Baskerville

# themes/paper/assets/main.css
# https://themes.gohugo.io/themes/hugo-paper/
theme = "paper"


copyright = "Copyright {year} Steve Isaacson"
logo = "false"

[params]
  # color style
  color = 'light'                 # linen, wheat, gray, light

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about"
    weight = 3
  [[menu.main]]
    identifier = "church"
    name = "WootCatChurch"
    title = "Church"
    url = "https://wootcatchurch.com"
    weight = 4

# https://stackoverflow.com/questions/63198652/hugo-shortcode-ignored-saying-raw-html-omitted


[markup.goldmark.renderer]
    unsafe= true

